### ISSUE TITLE
ROS 2

### ISSUE THREAD

**Issue by mhubii** [robot-learning-freiburg/ros_sam#1]
Very cool tool. Thanks for sharing. Are there any plans to make it available in ROS 2?

**Comment by ARoefer** [comment]
Thank you @mhubii! I am afraid that neither of our groups are currently using ROS2 and that will also not change for the foreseeable future, so we will not offer that support any time soon.

However, if you felt like contributing a ROS2 version, we would of course welcome it! I don't know how difficult a port would be. I think the ROS2 concepts are the same, but the API has changed.

**Comment by darshit-desai** [comment]
Hi @mhubii @ARoefer if you want to collaborate on a ROS2 version I can contribute

**Comment by mhubii** [comment]
this should be relatively straight forward, drafted some: see https://github.com/mhubii/ros_sam

where would this PR be aimed against?

would there just be a ros2 branch in this repo? Let me know if it exists so I can aim the PR against it

**Comment by mhubii** [comment]
@ARoefer may I ask what the `rqt_image_view_seg` is?

**Comment by ARoefer** [comment]
@mhubii For a ROS2 version of this package, I'd say we can have a `ros2` branch. I have created it so you can send your PR there.

 `rqt_image_view_seg` is a panel for rqt that allows you to manually set a segmentation point query on an image coming from a topic. The resulting mask will be sent out on a topic and can thus be used as a manual way to kick off your pipeline. That is how we use it in our recent paper.

**Comment by mhubii** [comment]
there is no ROS 2 support for `rqt_image_view_seg`

**Comment by mhubii** [comment]
Hi @darshit-desai , thank you for offering your kind help. The server is working in ROS 2. If you'd like to have a look at supporting interactive segmentation in ROS 2 that would be amazing for the community !

You could investigate rviz plugins with SAM client that requests the SAM server or rqt image viewer modification as was done here.

Might be best to open a new issue for that purpose.

**Comment by ARoefer** [comment]
Hi @mhubii,

I have been thinking about it and wondered, if it would not be easier to split the ros1 and ros2 versions. If you were okay with hosting the ros2 version, I'd link to your repo in the readme of this one and vice versa, so it's easy to change versions if Google presents the wrong result.
What do you think?

**Comment by mhubii** [comment]
I mean this is your work so you should take the full credit for it. It also helps the community to minimize redundancy.

It should be relatively simple to merge ROS 1 / 2 changes once the code is re-structured a la https://github.com/robot-learning-freiburg/ros_sam/pull/4. For that you could have a brief look at the PR or just implement it yourself briefly.

What would have to be done is to turn the `ros_sam_msgs` into a separate package. But either way is fine, the ROS 2 version can just live on a fork.

But maybe for my understanding. Do you mean hosting it as an independent repo, i.e. not a fork?

**Comment by darshit-desai** [comment]
Or maybe just make two different branches in the repo itself one for ROS 1 one for ROS2

**Comment by ARoefer** [comment]
@mhubii I did mean as a fork. I don't think there's any downside to that? Yeah, I get that point. Let's keep the two-branch solution. My problem is just, that I am still busy, so I am still unable to review your PR, and I feel bad keeping you waiting for feedback.

**Comment by mhubii** [comment]
no problem at all
