### ISSUE TITLE
Text as prompt

### ISSUE THREAD

**Issue by Taeyoung96** [robot-learning-freiburg/ros_sam#6]
@raabuchanan   

Thanks for the great work!  

I have a question about using the SAM model with text prompts.

According to https://github.com/facebookresearch/segment-anything/issues/93, Is it essential to use a model like Grounding-DINO to utilize text prompts?

If so, can you give me a guideline on what I need to modify in this ROS package?

I'd be grateful for an answer.

Thanks,

**Comment by ARoefer** [comment]
Hi @Taeyoung96,

I'm afraid we have no idea how to use text prompts with SAM. As it stands, it is not an officially supported feature by the original authors and thus we do offer a solution here. I have seen multiple ways of trying to attach text-prompts to SAM and I think they all have their advantages and drawbacks.

If you want to make your own solution though, you'd have to modify `src/ros_sam/sam.py` for the actual processing of the query, `scripts/sam_node.py` for the node offering your query type and optionally `src/ros_sam/sam_client.py` if you want to hide the message generation step when you use the query.

Hope this helps.

**Comment by Palpatineli** [comment]
@ARoefer I'm sorry for necroing this issue, but do you know if there is a list somewhere for the different ways to attach text-prompts to SAM, preferably with pros and cons?

**Comment by ARoefer** [comment]
Hello, I'm afraid I'm also not in the know on this. This is the only thing I found from a Google search: https://github.com/facebookresearch/segment-anything/issues/4
I think there's a better list somewhere but I don't know where. "Segment Everything Everywhere At Once" comes to mind.
